version: '3.8'

networks:
  sape:
    name: sape
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: django-db
      POSTGRES_USER: sape-django
      POSTGRES_PASSWORD: "!@BenSape"
    ports:
      - "5432:5432"
    volumes:
      - sape-data:/var/lib/postgresql/data
    networks:
      - sape

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - sape
    depends_on:
      - db

volumes:
  sape-data: