# Generated by Django 5.0.3 on 2024-03-20 00:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('winter', 'WINTER'), ('summer', 'SUMMER'), ('spring', 'SPRING'), ('fall', 'FALL'), ('all', 'ALL')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('why_its_bad', models.TextField()),
                ('why_its_good', models.TextField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='patterns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reputation', models.IntegerField()),
                ('ecoreputation', models.IntegerField()),
                ('description', models.TextField()),
                ('why_its_bad', models.TextField()),
                ('why_its_good', models.TextField()),
                ('material_used', models.TextField()),
                ('fabrication_location', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ManyToManyField(to='clothes.material')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes')),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), default=list, size=None)),
                ('weather', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothestype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('principal_material', models.ManyToManyField(to='clothes.material')),
                ('secondary_material', models.ManyToManyField(related_name='secondary_material', to='clothes.material')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.pattern')),
            ],
        ),
    ]
