# Generated by Django 5.0.3 on 2024-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
