# Generated by Django 5.0.3 on 2024-03-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothing_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.brand'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.pattern'),
        ),
    ]
